import remotion from "@remotion/eslint-plugin";
import type { Linter } from "eslint";
import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";
import storybook from "eslint-plugin-storybook";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Remotion-specific lint rules, scoped to the compositions folder. We use
  // the bare plugin (not `@remotion/eslint-config-flat`) on purpose: the full
  // flat config bundles its own typescript-eslint + react-hooks, which collide
  // with eslint-config-next's `@typescript-eslint` plugin ("Cannot redefine
  // plugin"). `flatPlugin` ships only the `@remotion/*` rules.
  // Same type-only RuleModule/RuleDefinition clash as the storybook spread
  // below — cast the assembled config to the flat-config element type.
  {
    files: ["remotion/**/*.{ts,tsx}"],
    ...remotion.flatPlugin,
  } as unknown as Linter.Config,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Vendor-generated by `shadcn add` / Next.js scaffold; do not edit.
    "components/ui/**",
    "hooks/use-mobile.ts",
    // Auto-generated from Strava's OpenAPI spec via `bun run strava:types`.
    "lib/strava-api.generated.ts",
    // Vendored agent skills installed via `npx skills add`, pinned by
    // skills-lock.json. Third-party content — re-add/update, don't edit.
    "skills/**",
    // Generated, gitignored test artifacts — Playwright's HTML report bundles
    // minified vendor JS that eslint would otherwise flag by the thousands.
    "playwright-report/**",
    "test-results/**",
    "coverage/**",
    // Gitignored Storybook build output — minified vendor bundles.
    "storybook-static/**",
  ]),
  // eslint-plugin-storybook declares its rules with RuleModule types from an
  // older typescript-eslint whose RuleContext shape no longer matches
  // eslint/config's RuleDefinition. The clash is type-only — runtime is fine —
  // so we cast the recommended config to the flat-config element type.
  ...(storybook.configs["flat/recommended"] as Linter.Config[]),
]);

export default eslintConfig;
