// For more info, see https://github.com/storybookjs/eslint-plugin-storybook#configuration-flat-config-format

import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";
import storybook from "eslint-plugin-storybook";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Vendor-generated by `shadcn add` / Next.js scaffold; do not edit.
    "components/ui/**",
    "hooks/use-mobile.ts",
    // Auto-generated from Strava's OpenAPI spec via `bun run strava:types`.
    "lib/strava-api.generated.ts",
    // Generated, gitignored test artifacts — Playwright's HTML report bundles
    // minified vendor JS that eslint would otherwise flag by the thousands.
    "playwright-report/**",
    "test-results/**",
    "coverage/**",
    // Gitignored Storybook build output — minified vendor bundles.
    "storybook-static/**",
  ]),
  ...storybook.configs["flat/recommended"],
]);

export default eslintConfig;
